### ISSUE TITLE
[2.1.1] Server hanging & Player Disconnecting

### ISSUE THREAD

**Issue by crazzyt9** [Eco-DiscordLink/EcoDiscordPlugin#32] opened 2021-02-07 17:17 UTC
So it seems that the DiscordLink is slowing my server down and even causing people to disconnect due to the following error/warnings pictured

Another issue I've noticed, is the bot will randomly just stop working either all together or just from discord side (Meaning it'll pass eco stuff to discord, but not discord messages to eco).

Is there something that I have setup or configured wrong?

If you need more information please let me know what I can do to help.
I've attached the pluginlog as well.

Eco Server version 9.2.4

![DiscordLinkErrors](https://user-images.githubusercontent.com/41900266/107153747-fcbdc880-6923-11eb-8d36-dec6babd7b52.png)
[Pluginlog.txt](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/files/5939475/Pluginlog.txt)

**Comment by MonzUn** [comment] 2021-02-08 02:42
Hey! Sorry that you're having issues.
Something is spamming if you are actually hitting the rate limit (either that, or Discord is having a bad day).
Does this behavior come back if you restart the plugin (?dl-restart) or the server?

Could you also try to disable the chat log?
It seems to be having issues when looking in the log. Shouldn't be related, but with these types of tricky issues it's nice to rule stuff out :)

I will also be releasing a new version in a few days. Since I don't know what the issue is, I don't know if it will solve this, but using that is something to try as well.

**Comment by crazzyt9** [comment] 2021-02-08 02:55
Sadly yes, this is happening within a few minutes after a server restart, I'll re-enable the DiscordLink after our next restart and try your suggestions  I haven't tried a dl-restart, is that something I would enter into the command console?

Also looking forward to the update :) Hopefully it resolves the issue however if not I'll keep ya informed.

**Comment by crazzyt9** [comment] 2021-02-09 02:11
So After re enabling DiscordLink and starting the server it did the same thing over loading the server and DC'ing everyone

This time however the console didn't show any errors or warnings instead it was frozen

**Comment by drkshrk** [comment] 2021-02-09 13:24
1) Which version of Discord Link are you using?

2) is this self hosted or a server at a host?

Just a couple points to start with

**Comment by crazzyt9** [comment] 2021-02-09 17:12
I'm using discordlink 2.1.1

Self hosted server in a VM
9KM world
Threadripper 2970WX 24 core CPU (8 cores to the VM)
24gb ramp to VM

**Comment by MonzUn** [comment] 2021-02-09 23:49
Hm, I've had another user report something similar. Would you be able to zip up your server (skipping backup files) and link it to me so I can run it in a debugger?

It seems like some system is ending up in an infinite loop or something. The other person who had this issue had the log spammed with threshold warnings though, so it's not the exact same thing if your logs are silent.

And yes, dl-restart is both an Eco and Discord command. It likely won't fix anything though if you have already restarted the whole server.

If you want to test 2.0.0, there is a pre-release on the Discord linked on the main page of this repo :)

**Comment by crazzyt9** [comment] 2021-02-10 00:18
It's a rather large download about a half GB but here it is,

http://kingsofeden.net/NewEdenBeforeStackMod1.zip

**Comment by drkshrk** [comment] 2021-02-10 00:20
@MonzUn would the version of em-framework effect anything?

Attached is the build I am using which is a development build but it works fine for the players on my server and myself.
[DiscordLink Unofficial.zip](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/files/5955004/DiscordLink.Unofficial.zip)

**Comment by crazzyt9** [comment] 2021-02-10 02:34
HA didn't even think about that, I removed the dl link and will replace it here shortly thanks for the catch.

**Comment by crazzyt9** [comment] 2021-02-10 02:41
Okay two links now  

http://kingsofeden.net/NewEdenBeforeStackMod1.zip  (updated without api key)

http://kingsofeden.net/DiscordLink_Crazzyt9.zip (for the mod folder so you don't have to download the entire server again!)

**Comment by crazzyt9** [comment] 2021-02-10 03:48
Would it be possible for you guys to change the name of the server when you put it up please, people are getting confused and joining the wrong one  I didn't think to change the name before hand.

**Comment by drkshrk** [comment] 2021-02-10 04:32
Sorry about that I thought I had it marked private 🤦🏻‍♂️

**Comment by MonzUn** [comment] 2021-02-10 08:09
Sorry, yeah I should have asked you to remove the key and set it as private in network.eco.

@drkshrk, the em-framework version can definitely affect things, but the one in 2.1.1 and 2.2.0 are almost the same.
Fyre jyst fixed the issue with the command log not working.

I'm glad that 2.2.0 seems to work for you, but I'm still going to check what 2.1.1 is doing!

**Comment by NHDriver4** [comment] 2021-02-12 03:17
Also seeing this issue. Willing to provide logs and debug output if needed. Logging was enabled, however disabling did not resolve. v2.1.1

**Comment by MonzUn** [comment] 2021-02-12 11:47
I'm leaning towards just letting people update to 2.2.0 to solve it.
This version ahs been out for almost 4 months and it's only in the last month several people have started getting this issue, so there is probably some incompatibility between Eco 0.9.2 and DL 2.1.1, which is why DL 2.2.0 works.

**Comment by drkshrk** [comment] 2021-02-12 12:17
Forced obsolescence 😂

**Comment by crazzyt9** [comment] 2021-02-13 16:58
Bad news I just looked at my console and it seems I'm having the warnings again, (We usually restart our server every 12ish hours and hadn't been seeing them)  I got into a minor car accident yesterday and wasn't able to do a restart at all and when i opened up my VM to do so clicked on the console and it "unfroze itself" and spammed with the ratelimitpre warning  Doing a restart now and will keep my eye on it.

**Comment by crazzyt9** [comment] 2021-02-13 17:20
Okay and another update, it seems that Now we're getting the warnings and errors again

**Comment by MonzUn** [comment] 2021-02-14 17:12
The double posting is a known but that occurs sometimes when the bot reconnects.
Should be unrelated to the issue at hand and a plugin restart fixes it.

The warnings are normal to get. Are you still getting the errors though?

**Comment by crazzyt9** [comment] 2021-02-14 17:42
I've seen the error a couple times, but nothing like the last version

**Comment by MonzUn** [comment] 2021-02-15 14:09
Ok and it's not causing lag spikes that kick players out of the game anymore?

**Comment by crazzyt9** [comment] 2021-02-15 15:31
It hasn't as of yet that we've noticed.

**Comment by MonzUn** [comment] 2021-02-15 19:02
OK, lets leave this open for a few more days and otherwise conclude that 2.2.0 solves it.

**Comment by MonzUn** [comment] 2021-02-28 12:36
As 2.2.0 seems to resolve this issue and that is now released, I will go ahead and close this issue for now. Make sure to report back again if it resurfaces!

**Closed by MonzUn** 2021-02-28 12:36 UTC
Labels: Cannot Reproduce, Major, bug
